[package]
name = "gp-organizer"
version = "0.1.0"
authors = ["Tamás Szelei"]

[dependencies]
glob = "0.2.11"
docopt = "0.8"
docopt_macros = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
kamadak-exif = "0.2.3"